version = "4.4.1"

source = "gnu"
directory = "make"
archive = "make-4.4.1.tar.gz"
extracted_name = "make-4.4.1"
sha256 = "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3"
configure = "./configure --prefix=/usr"
build = "make -j$(nproc)"
install = "make install"
